### PR TITLE
Add Linux mimetype stuff

### LINKED ISSUE #387: [Feature] - Adding .btm file type and association on Linux?
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

https://aur.archlinux.org/packages/bambootracker-git/#comment-816368

Is it practical to add a new MIME type for .btm files, associated with BambooTracker by default?

> this sounds like an upstream issue rather than packaging. The source should provide a xdg mimetype description along with a desktop file update to match.

Currently, BambooTracker ships a .desktop file (https://github.com/BambooTracker/BambooTracker/blob/master/data/applications/BambooTracker.desktop) but not a MIME .xml file. Is it possible to add a MIME .xml file, edit the .desktop file to add a `MimeType` key including the new MIME type, and automatically install the XML file upon `make install` (so it will get picked up by AUR packaging)?

### PR DESCRIPTION
**Pull request by OPNA2608**
Closes #387, CC @nyanpasu64

Untested cuz I don't use mimetype association stuff. Looked at some examples & the freedesktop specs, I hope this is correct?

### CODE REVIEW

**Comment by nyanpasu64** [comment]
Maybe `audio/x-btm` instead of `application/x-btm`? maybe not. .it and .s3m is audio/, but .pdf and .docx are application/, and I *think* .btm files are intended for editing and not playback (you export in order to play a file)? not sure.

didn't test the PR otherwise, i'm implementing some stuff in tenacity/audacity lately.

**Comment by nyanpasu64** [comment]
```
(5/5) Updating the MIME type database...
/usr/share/mime/packages/application-x-btm.xml:7: parser error : Opening and ending tag mismatch: expaned-acronym line 7 and acronym
    <expaned-acronym>BambooTracker Module</acronym>
                                                   ^
/usr/share/mime/packages/application-x-btm.xml:8: parser error : Opening and ending tag mismatch: expaned-acronym line 7 and acronym
    <expaned-acronym xml:lang="de">BambooTracker-Modul</acronym>
```

It should be spelled `expanded-acronym` (not expaned), and use the same tag to open and close.

**Comment by nyanpasu64** [comment]
Seems to work fine in KDE, when installed using the Arch PKGBUILD.

**Comment by OPNA2608** [comment]
Thanks for the feedback, merged.

**Pull request merged**
