### PR TITLE
Show Effect list track types as separate columns #489

### PR DESCRIPTION
**Pull request by cxong**
image

### CODE REVIEW

**Comment by cxong** [comment]
WIP, other things I want to do:

- Show checkboxes or tick symbol instead of "Yes"
- Remove "Track type" from translations
- Add sorting to table

**Comment by cxong** [comment]
image
I decided against checkboxes because they look bad; using a tick symbol instead

**Comment by rerrahkr** [comment]
LGTM. Colud you mind me mergeing this PR?

**Comment by rerrahkr** [comment]
Thank you for your contribution!

**Pull request merged**
