### PR TITLE
Fix lupdate warnings

### LINKED ISSUE #390: [Windows|macOS|Linux|BSD] - lupdate warnings
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

`lupdate` emits various warnings about the code that uses `tr()` and similar functions.

```
BambooTracker/gui/configuration_dialog.cpp:71: tr() cannot be called without context
BambooTracker/gui/configuration_dialog.cpp:72: tr() cannot be called without context
BambooTracker/gui/effect_description.cpp:43: Class 'effect_desc' lacks Q_OBJECT macro
BambooTracker/gui/file_io_error_message_box.cpp:32: tr() cannot be called without context
BambooTracker/gui/file_io_error_message_box.cpp:33: tr() cannot be called without context
BambooTracker/gui/file_io_error_message_box.cpp:34: tr() cannot be called without context
BambooTracker/gui/file_io_error_message_box.cpp:35: tr() cannot be called without context
BambooTracker/gui/file_io_error_message_box.cpp:36: tr() cannot be called without context
BambooTracker/gui/file_io_error_message_box.cpp:37: tr() cannot be called without context
BambooTracker/gui/instrument_editor/instrument_editor_drumkit_form.cpp:39: tr() cannot be called without context
BambooTracker/gui/instrument_editor/instrument_editor_drumkit_form.cpp:39: tr() cannot be called without context
BambooTracker/gui/instrument_editor/instrument_editor_drumkit_form.cpp:39: tr() cannot be called without context
BambooTracker/gui/mainwindow.cpp:107: Class 'ModuleSaveCheckDialog' lacks Q_OBJECT macro
BambooTracker/gui/module_properties_dialog.cpp:37: tr() cannot be called without context
BambooTracker/gui/module_properties_dialog.cpp:38: tr() cannot be called without context
```

`Class '<class>' lacks Q_OBJECT macro` is very straightforward: The class from which `tr()` (or one of its wrappers like `QT_TR_NOOP()`) is used lacks the `Q_OBJECT` macro. [From the Qt archive (at least 19yo!):](https://doc.qt.io/archives/qq/qq03-swedish-chef.html)

> **5. Forgetting a Q_OBJECT.**
> 
> Every now and then, somebody comes to my office and says "tr() doesn't work!" I then spend half an hour trying to isolate the problem, recompiling Qt with qDebug() statements in the QTranslator code, to finally discover that the tr() call appeared in a class with no Q_OBJECT macro. The Q_OBJECT macro is necessary for signals, slots, properties, and tr(). Without it, tr() uses the name of the base class as the context, whereas lupdate still uses the name of the class in question. Recent versions of lupdate recognize this blunder and emit a warning ("Class MyClass lacks Q_OBJECT macro").

`tr() cannot be called without context`, based on [these](https://forum.qt.io/topic/77873/qt_tr_noop-gives-cannot-be-called-without-context) [two](https://forum.qt.io/topic/104211/qt_tr_noop-does-not-get-recognized-from-lupdate) Qt forum posts, seems to suggest that we should use `QT_TRANSLATE_NOOP()` instead of `QT_TR_NOOP()` on translatable strings outside of functions (belonging to QObject-derived classes).

Fixing these warnings might cause some translations to get lost since their TS contexts will migrate from a placeholder value to a named context (i.e. the effect descriptions are in a namespace, not a class where `Q_OBJECT` would work, so `QT_TRANSLATE_NOOP()` will be used), but we're already lacking translations after recent commits so it shouldn't be that much of a problem.

## How to reproduce

1. Run `lupdate Project.pro`

## System Information

- **Operating System**: NixOS Linux 21.05
- **BambooTracker Version**: master
- **Build Type**: local

### PR DESCRIPTION
**Pull request by OPNA2608**
Closes #390.

Some existing translations will break after this due to `lupdate` not being very smart & losing existing translations in some context migrations.

### CODE REVIEW

**Comment by OPNA2608** [comment]
Sooo this fixes all warnings in the CI runs with newer Qt, but still leaves abunch of warnings when running `lupdate` on Ubuntu 16.04…

<details>

```
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/instrument_editor/pan_macro_editor.cpp:39: Qualifying with unknown namespace/class ::PanMacroEditor
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/instrument_editor/tone_noise_macro_editor.cpp:35: Qualifying with unknown namespace/class ::ToneNoiseMacroEditor
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1348: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1369: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1700: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1719: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1764: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1810: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1874: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1931: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1963: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:1974: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2061: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2090: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2095: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2100: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2105: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2110: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2115: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2223: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2224: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2252: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2253: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2326: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2403: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2404: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2504: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2504: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2516: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2518: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2533: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2544: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2583: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2585: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2876: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2952: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2952: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2974: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2976: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2979: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2980: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2983: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2984: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2985: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2989: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2991: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2992: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2993: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2994: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2995: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2996: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2997: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:2999: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3001: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3002: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3019: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3189: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3191: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3191: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3256: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3257: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3257: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3326: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3347: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3376: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3378: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3378: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3389: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3410: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3416: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3511: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3513: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3513: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3522: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3522: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3579: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3581: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3581: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3590: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3590: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3688: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3748: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3851: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3894: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3915: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:3969: tr() cannot be called without context
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/mainwindow.cpp:696: Unbalanced opening parenthesis in C++ code (or abuse of the C++ preprocessor)
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/instrument/bank.cpp:83: Ignoring definition of undeclared qualified class
```

</details>

**Comment by OPNA2608** [comment]
Seems like most of these were caused by the raw string in the welcome dialogue. While supported by the compiler, `lupdate` from that old Qt versions seems to have a problem with understanding them so I had to remove it, otherwise `lupdate` would consider all translations in mainwindow.cpp as "vanished"…

<details>
  <summary>Just left with these warning on Ubuntu 16.04 now

```
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/instrument_editor/pan_macro_editor.cpp:39: Qualifying with unknown namespace/class ::PanMacroEditor
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/gui/instrument_editor/tone_noise_macro_editor.cpp:35: Qualifying with unknown namespace/class ::ToneNoiseMacroEditor
/home/runner/work/BambooTracker/BambooTracker/BambooTracker/instrument/bank.cpp:83: Ignoring definition of undeclared qualified class
```

</details>

**Review by rerrahkr — COMMENTED** [review]
It looks fine for me.
I've been coding without knowing much about Qt, so there were some parts that didn't work well, and the source code is hard to understand. Thanks again for your help.

**Comment by OPNA2608** [comment]
Thanks for the quick check!

**Comment by OPNA2608** [comment]
This broke the actual translation of the strings in the UI, I'll open a fixup PR later today.

**Pull request merged**
